" No need for compatibility with vi
set nocompatible

" Set XDG based state files
if empty($XDG_STATE_HOME)
  let $XDG_STATE_HOME = $HOME . '/.local/state'
endif

let s:xdg_base = $XDG_STATE_HOME . '/vim'

for dir in ['swap', 'backup', 'undo', 'view']
  call mkdir(s:xdg_base . '/' . dir, 'p')
endfor

set undofile
execute 'set viminfofile=' . fnameescape(s:xdg_base . '/viminfo')
execute 'set directory^=' . fnameescape(s:xdg_base . '/swap//')
execute 'set backupdir^=' . fnameescape(s:xdg_base . '/backup//')
execute 'set undodir^=' . fnameescape(s:xdg_base . '/undo//')
execute 'set viewdir^=' . fnameescape(s:xdg_base . '/view//')

" Jump to the last cursor position
augroup remember_cursor
  autocmd!
  autocmd BufReadPost *
        \ if line("'\"") > 0 && line("'\"") <= line("$") |
        \   execute "normal! g`\"" |
        \ endif
augroup END

" Status bar customizations
let g:airline_powerline_fonts = 1
let g:airline_theme = 'onedark'
let g:airline_section_z = '%l:%c'

" Color theme settings
let g:onedark_termcolors = 256
let g:onedark_hide_endofbuffer = 1
let g:onedark_terminal_italics = 1

" Deoplete settings
" call deoplete#enable()

" ALE settings
let g:ale_fix_on_save = 1
let g:ale_fixers = {
			\ '*': ['remove_trailing_lines', 'trim_whitespace'],
			\ }

" Enable color theme
syntax on
colorscheme onedark

" Custom settings
set number
set autoindent
set smartindent
set smarttab
set expandtab
set tabstop=4
set shiftwidth=4
